# Generated by Django 5.2.3 on 2025-09-08 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Newsletter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("is_subscribed", models.BooleanField(default=True)),
                ("date_subscribed", models.DateTimeField(auto_now_add=True)),
                ("date_unsubscribed", models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
