# Generated by Django 5.2.3 on 2025-06-29 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_alter_product_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.CharField(
                choices=[
                    ("Alloy Wheels", "Alloy Wheels"),
                    ("Track Edition", "Track Edition"),
                ],
                default="Alloy Wheels",
                max_length=50,
            ),
        ),
    ]
