# Generated by Django 5.2.3 on 2025-08-01 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_order_cartitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="brand",
            field=models.CharField(
                choices=[
                    ("BBS", "BBS"),
                    ("OZ Racing", "OZ Racing"),
                    ("Enkei", "Enkei"),
                    ("Fox", "Fox"),
                ],
                default="BBS",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="size",
            field=models.CharField(
                choices=[
                    ('17"', '17"'),
                    ('18"', '18"'),
                    ('19"', '19"'),
                    ('20"', '20"'),
                ],
                default='18"',
                max_length=10,
            ),
        ),
    ]
