# Generated by Django 5.2.3 on 2025-08-04 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0006_product_brand_product_size"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="weight",
            field=models.CharField(
                choices=[
                    ("7-10", "7-10 kg"),
                    ("10-13", "10-13 kg"),
                    ("13-17", "13-17 kg"),
                ],
                default="7-10",
                max_length=10,
            ),
        ),
    ]
