# Generated by Django 5.2.3 on 2025-09-07 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0009_order_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="delivery_estimate",
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name="product",
            name="material",
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name="product",
            name="pack_size",
            field=models.PositiveSmallIntegerField(
                default=1, help_text="Items per pack (1 or 4)"
            ),
        ),
    ]
