# Generated by Django 5.2.3 on 2025-09-07 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0010_product_delivery_estimate_product_material_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="description_long",
            field=models.TextField(blank=True),
        ),
    ]
